version: '3.4'

services:

  bedviewmock:
    container_name: bedviewmock
    image: ${DOCKER_REGISTRY-}bedviewmock
    build:
      context: .
      dockerfile: src/BedViewMock/Dockerfile
    ports: 
      - "35001:80"
    environment:
        Jwt__SigningKey: WmZq4t7w!z%C*F)J@NcRfUjXn2r5u8x/
        Jwt__EncryptionKey: z%C*F-JaNcRfUjXn                        